[watch]
watch = [
    "src/",
    "Cargo.toml",
    "Cargo.lock",
    "index.html",
    "input.css",
    "tailwind.config.js",
]

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-i", "input.css", "-o", "./tailwind.css", "-m"]
