name: build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build opal
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('scripts/npm_dependencies.sh') }}

      - name: Install npm dependencies
        run: |
          ./scripts/npm_dependencies.sh

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install trunk and wasm-bindgen-cli
        run: |
          cargo install trunk --version ~0.16 --locked
          cargo install wasm-bindgen-cli --version ~0.2 --locked

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Setup DBs
        run: |
          pip install -r ./scripts/cmudict/requirements.txt
          ./setup.sh

      - name: Build
        run: |
          TRUNK_BUILD_PUBLIC_URL="/opal/" trunk build --release

      - name: Optimize with binaryen and wasm-opt
        run: |
          python3 ./scripts/optimize.py ./dist
