name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  # Assign commit authorship to official Github Actions bot when pushing to the `web-deploy` branch:
  GIT_USER: "github-actions[bot]"
  GIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"

jobs:
  build:
    name: Build opal
    uses: ./.github/workflows/build.yml
    with:
      artifact: true
    secrets: inherit

  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Download build for distribution
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
          path: ./dist

      - name: Configure git user and email
        run: |
          git config --global user.name ${GIT_USER}
          git config --global user.email ${GIT_EMAIL}
          echo Name: $(git config --get user.name)
          echo Email: $(git config --get user.email)

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: web-deploy

      - name: Delete the artifact after success
        uses: geekyeggo/delete-artifact@176a747ab7e287e3ff4787bf8a148716375ca118 # v6.0.0
        with:
          name: dist
          failOnError: false
